import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/accounts.ts',
    'src/audit.ts',
    'src/backups.ts',
    'src/canonical.ts',
    'src/collaboration.ts',
    'src/problems.ts',
    'src/http.ts',
    'src/clients.ts',
    'src/corpus.ts',
    'src/live.ts',
    'src/live-media.ts',
    'src/live-mode.ts',
    'src/live-state.ts',
    'src/live-theme.ts',
    'src/jobs.ts',
    'src/entities.ts',
    'src/integrations.ts',
    'src/layouts.ts',
    'src/library.ts',
    'src/media.ts',
    'src/order.ts',
    'src/palette.ts',
    'src/portable.ts',
    'src/presence.ts',
    'src/revisions.ts',
    'src/runs.ts',
    'src/service-templates.ts',
    'src/sessions.ts',
    'src/snapshots.ts',
    'src/services.ts',
    'src/content-languages.ts',
    'src/slide-groups.ts',
    'src/slide-labels.ts',
    'src/songs.ts',
    'src/sermons.ts',
    'src/sermon-import.ts',
    'src/pptx.ts',
    'src/scripture.ts',
    'src/totp.ts',
    'src/translation-offsets.ts',
    'src/workspace.ts',
    'src/webauthn.ts',
  ],
  format: ['esm'],
  dts: true,
  clean: true,
  sourcemap: true,
  // The browser is the narrowest runtime the contracts have to work in, and the browser-safety gate
  // in scripts/workspace keeps the source free of anything Node-only, so nothing here needs node24.
  target: 'es2023',
});
