/**
 * Every name a sermon file is allowed to call a book, per USFM code: English, German and Tamil,
 * plus the English variants people actually type. `resolveBook` matches these ignoring case,
 * spacing and punctuation, and reads a leading ordinal in any form ("1", "1st", "I", "First"),
 * so "2nd Samuel", "2. Samuel" and "II Samuel" all need one entry between them.
 *
 * The canon's own names (see PROTESTANT_CANON) are indexed as well and are not repeated here.
 * To add a language, append its 66 names to the rows.
 */
export const BOOK_ALIASES: ReadonlyArray<readonly [usfm: string, ...names: string[]]> = [
  ['GEN', 'Genesis', '1. Mose', 'ஆதியாகமம்'],
  ['EXO', 'Exodus', '2. Mose', 'யாத்திராகமம்'],
  ['LEV', 'Leviticus', '3. Mose', 'லேவியராகமம்'],
  ['NUM', 'Numbers', '4. Mose', 'எண்ணாகமம்'],
  ['DEU', 'Deuteronomy', '5. Mose', 'உபாகமம்'],
  ['JOS', 'Joshua', 'Josua', 'யோசுவா'],
  ['JDG', 'Judges', 'Richter', 'நியாயாதிபதிகள்'],
  ['RUT', 'Ruth', 'Rut', 'ரூத்'],
  ['1SA', '1 Samuel', '1. Samuel', '1 சாமுவேல்'],
  ['2SA', '2 Samuel', '2. Samuel', '2 சாமுவேல்'],
  ['1KI', '1 Kings', '1. Könige', '1 இராஜாக்கள்'],
  ['2KI', '2 Kings', '2. Könige', '2 இராஜாக்கள்'],
  ['1CH', '1 Chronicles', '1. Chronik', '1 நாளாகமம்'],
  ['2CH', '2 Chronicles', '2. Chronik', '2 நாளாகமம்'],
  ['EZR', 'Ezra', 'Esra', 'எஸ்றா'],
  ['NEH', 'Nehemiah', 'Nehemia', 'நெகேமியா'],
  ['EST', 'Esther', 'Ester', 'எஸ்தர்'],
  ['JOB', 'Job', 'Hiob', 'யோபு'],
  ['PSA', 'Psalms', 'Psalm', 'Psalmen', 'சங்கீதம்'],
  ['PRO', 'Proverbs', 'Sprüche', 'நீதிமொழிகள்'],
  ['ECC', 'Ecclesiastes', 'Prediger', 'பிரசங்கி'],
  ['SNG', 'Song of Songs', 'Canticles', 'Hohelied', 'உன்னதப்பாட்டு'],
  ['ISA', 'Isaiah', 'Jesaja', 'ஏசாயா'],
  ['JER', 'Jeremiah', 'Jeremia', 'எரேமியா'],
  ['LAM', 'Lamentations', 'Klagelieder', 'புலம்பல்'],
  ['EZK', 'Ezekiel', 'Hesekiel', 'எசேக்கியேல்'],
  ['DAN', 'Daniel', 'தானியேல்'],
  ['HOS', 'Hosea', 'ஓசியா'],
  ['JOL', 'Joel', 'யோவேல்'],
  ['AMO', 'Amos', 'ஆமோஸ்'],
  ['OBA', 'Obadiah', 'Obadja', 'ஒபதியா'],
  ['JON', 'Jonah', 'Jona', 'யோனா'],
  ['MIC', 'Micah', 'Micha', 'மீகா'],
  ['NAM', 'Nahum', 'நாகூம்'],
  ['HAB', 'Habakkuk', 'Habakuk', 'ஆபகூக்'],
  ['ZEP', 'Zephaniah', 'Zephanja', 'செப்பனியா'],
  ['HAG', 'Haggai', 'ஆகாய்'],
  ['ZEC', 'Zechariah', 'Sacharja', 'சகரியா'],
  ['MAL', 'Malachi', 'Maleachi', 'மல்கியா'],
  ['MAT', 'Matthew', 'Matthäus', 'மத்தேயு'],
  ['MRK', 'Mark', 'Markus', 'மாற்கு'],
  ['LUK', 'Luke', 'Lukas', 'லூக்கா'],
  ['JHN', 'John', 'Johannes', 'யோவான்'],
  ['ACT', 'Acts', 'Apostelgeschichte', 'அப்போஸ்தலர்'],
  ['ROM', 'Romans', 'Römer', 'Römerbrief', 'ரோமர்'],
  ['1CO', '1 Corinthians', '1. Korinther', '1 கொரிந்தியர்'],
  ['2CO', '2 Corinthians', '2. Korinther', '2 கொரிந்தியர்'],
  ['GAL', 'Galatians', 'Galater', 'Galaterbrief', 'கலாத்தியர்'],
  ['EPH', 'Ephesians', 'Epheser', 'Epheserbrief', 'எபேசியர்'],
  ['PHP', 'Philippians', 'Philipper', 'பிலிப்பியர்'],
  ['COL', 'Colossians', 'Kolosser', 'Kolosserbrief', 'கொலோசெயர்'],
  ['1TH', '1 Thessalonians', '1. Thessalonicher', '1 தெசலோனிக்கேயர்'],
  ['2TH', '2 Thessalonians', '2. Thessalonicher', '2 தெசலோனிக்கேயர்'],
  ['1TI', '1 Timothy', '1. Timotheus', '1 தீமோத்தேயு'],
  ['2TI', '2 Timothy', '2. Timotheus', '2 தீமோத்தேயு'],
  ['TIT', 'Titus', 'Titusbrief', 'தீத்து'],
  ['PHM', 'Philemon', 'Philemonbrief', 'பிலேமோன்'],
  ['HEB', 'Hebrews', 'Hebräer', 'Hebräerbrief', 'எபிரெயர்'],
  ['JAS', 'James', 'Jakobus', 'யாக்கோபு'],
  ['1PE', '1 Peter', '1. Petrus', '1 பேதுரு'],
  ['2PE', '2 Peter', '2. Petrus', '2 பேதுரு'],
  ['1JN', '1 John', '1. Johannes', '1 யோவான்'],
  ['2JN', '2 John', '2. Johannes', '2 யோவான்'],
  ['3JN', '3 John', '3. Johannes', '3 யோவான்'],
  ['JUD', 'Jude', 'Judas', 'யூதா'],
  ['REV', 'Revelation', 'Revelations', 'Offenbarung', 'வெளிப்படுத்தின விசேஷம்'],
];
