import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/main.ts',
    'src/migrate.ts',
    'src/deploy-preflight-cli.ts',
    'src/settings.ts',
    'src/boot.ts',
    'src/media.ts',
    'src/queue.ts',
    'src/repositories.ts',
    'src/backups.ts',
    'src/backup-retention.ts',
    'src/restores.ts',
    'src/restore-apply.ts',
    'src/sessions.ts',
    'src/migrations.ts',
  ],
  format: ['esm'],
  target: 'node24',
  platform: 'node',
  dts: {
    entry: [
      'src/settings.ts',
      'src/boot.ts',
      'src/media.ts',
      'src/queue.ts',
      'src/repositories.ts',
      'src/backups.ts',
      'src/backup-retention.ts',
      'src/restores.ts',
      'src/restore-apply.ts',
      'src/sessions.ts',
      'src/migrations.ts',
    ],
  },
  sourcemap: true,
  clean: true,
});
